######################################################################
# Automatically generated by qmake (3.0) Mon Jul 7 07:01:43 2014
######################################################################

QT+=core gui widgets sql network opengl
CONFIG += console
TEMPLATE = app
TARGET = QOglTest
INCLUDEPATH += . src

# Input
HEADERS += src/DateTime.h
SOURCES += src/DateTime.cpp src/QOglTest.cpp
