######################################################################
# Automatically generated by qmake (3.0) Wed Jul 9 23:12:20 2014
######################################################################

QT+=core gui widgets sql network opengl
CONFIG += console
LIBS += -framework GLUT
TEMPLATE = app
TARGET = QOglTest
INCLUDEPATH += . src

# Input
HEADERS += src/DateTime.h src/MainWidget.h
SOURCES += src/DateTime.cpp src/MainWidget.cpp src/QOglTest.cpp
